[profile.default]
src = "src"
out = "out"
libs = ["lib"]
OpenZeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.0.0" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
